# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI

on:
  push:
    branches: [ master ]

jobs:
  build-and-deploy:

    runs-on: ubuntu-latest

    environment: production

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14.x
        cache: 'npm'
    - name: Credentials
      run: |
        cd node
        node -e "require('fs').writeFileSync('credentials.json', '${{ secrets.GOOGLE_CREDENTIALS }}', {encoding: 'base64'});"
        node -e "require('fs').writeFileSync('token.json', '${{ secrets.GOOGLE_TOKEN }}', {encoding: 'base64'});"
    - name: Installation des modules
      run: npm i
    - name: Lancement du script
      run: npm run start
    - name: Upload
      uses: SamKirkland/FTP-Deploy-Action@4.2.0
      with:
        server: ${{ secrets.FTP_HOST }}
        username: ${{ secrets.FTP_USER }}
        password: ${{ secrets.FTP_PASSWORD }}
        server-dir: public_html/
        exclude: |
          **/.git*
          **/.git*/**
          **/node_modules/**
          **/node/**
          **/.settings/**
          .gitignore
          .project
          package*.json