# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14.x
        cache: 'npm'
    - name: Credentials
      run: |
        cd node
        echo "${{ secrets.GOOGLE_CREDENTIALS }}" > credentials.json
        echo "${{ secrets.GOOGLE_TOKEN }}" > token.json
        cat credentials.json
        cat token.json
    - name: Installation des modules
      run: npm i
    - name: Lancement du script
      run: npm run start
